export const VICTORIA_PUBLIC_PARKING_SOURCE_CATALOG = {
  summary: {
    scope:
      "Victoria public parking data is council-by-council. There is no single authoritative statewide parking zone and bay dataset.",
    recommendedRollout: [
      "City of Melbourne",
      "City of Ballarat",
      "City of Casey",
      "City of Greater Geelong",
    ],
  },
  tier1: [
    {
      id: "melbourne-on-street-bays",
      owner: "City of Melbourne",
      name: "On-street Parking Bays",
      url: "https://discover.data.vic.gov.au/dataset/on-street-parking-bays",
      dataShape: "geojson",
      entityType: "bay_polygon",
      publicAccess: "public on-street",
      confidence: "official_api",
      priority: 1,
      updateCadence: "live platform dataset; metadata last updated 2024-06-13",
      importStrategy: "Primary Melbourne bay geometry source.",
      notes:
        "Spatial polygons for individual parking bays. Best base layer for Melbourne bay references.",
    },
    {
      id: "melbourne-bay-restrictions",
      owner: "City of Melbourne",
      name: "On-street Car Park Bay Restrictions",
      url: "https://discover.data.vic.gov.au/dataset/on-street-car-park-bay-restrictions",
      dataShape: "tabular",
      entityType: "bay_rule",
      publicAccess: "public on-street",
      confidence: "official_api",
      priority: 1,
      updateCadence: "live platform dataset; metadata last updated 2024-06-13",
      importStrategy: "Join to Melbourne bay and sensor datasets using published join keys.",
      notes:
        "Contains rule windows and restriction details per bay. Required to turn Melbourne bays into usable parking products.",
    },
    {
      id: "melbourne-bay-sensors",
      owner: "City of Melbourne",
      name: "On-street Parking Bay Sensors",
      url: "https://discover.data.vic.gov.au/dataset/on-street-parking-bay-sensors",
      dataShape: "geojson",
      entityType: "bay_sensor",
      publicAccess: "public occupancy",
      confidence: "official_api",
      priority: 1,
      updateCadence: "metadata last updated 2025-02-13",
      importStrategy: "Optional live occupancy enrichment for Melbourne bays.",
      notes:
        "Sensor status source for live occupancy or confidence signals. Keep logically separate from static zone geometry.",
    },
    {
      id: "ballarat-zones",
      owner: "City of Ballarat",
      name: "Car Parking Zones",
      url: "https://discover.data.vic.gov.au/dataset/car-parking-zones",
      dataShape: "geojson",
      entityType: "zone_polygon",
      publicAccess: "public zones",
      confidence: "official_geojson",
      priority: 1,
      updateCadence: "monthly automated schedule; metadata last updated 2024-09-14",
      importStrategy: "Direct zone import into parking_zones after zone type normalization.",
      notes: "Cleanest non-Melbourne zone source. Good first council after Melbourne.",
    },
    {
      id: "casey-restriction-zones",
      owner: "City of Casey",
      name: "City of Casey Parking Restriction Zones",
      url: "https://discover.data.vic.gov.au/dataset/city-of-casey-parking-restriction-zones",
      dataShape: "geojson",
      entityType: "zone_polygon",
      publicAccess: "public restriction zones",
      confidence: "official_geojson",
      priority: 1,
      updateCadence: "continual; metadata last updated 2026-03-11",
      importStrategy: "Direct zone import into parking_zones with normalized rule text.",
      notes:
        "Strong council-maintained polygon source with current metadata. Likely one of the best refresh cadences in Victoria open data.",
    },
    {
      id: "geelong-parking-lots",
      owner: "City of Greater Geelong",
      name: "Parking Lots",
      url: "https://discover.data.vic.gov.au/dataset/parking-lots",
      dataShape: "geojson",
      entityType: "lot_or_zone",
      publicAccess: "public parking facilities",
      confidence: "official_geojson",
      priority: 1,
      updateCadence: "metadata last updated 2024-06-13",
      importStrategy: "Import as parking_zones or a future parking_facilities table depending on geometry fields.",
      notes:
        "Represents off-street lots with sensor context rather than kerbside restriction zones.",
    },
    {
      id: "geelong-sensor-occupancy",
      owner: "City of Greater Geelong",
      name: "Parking Sensor - Occupancy",
      url: "https://discover.data.vic.gov.au/dataset/parking-sensor-occupancy",
      dataShape: "geojson",
      entityType: "space_sensor",
      publicAccess: "public occupancy",
      confidence: "official_geojson",
      priority: 1,
      updateCadence: "metadata last updated 2024-06-13",
      importStrategy: "Optional live occupancy enrichment for Geelong spaces or lots.",
      notes:
        "Useful for live availability, but should remain separate from static zone references.",
    },
  ],
  tier2: [
    {
      id: "melbourne-zones-linked-to-street-segments",
      owner: "City of Melbourne",
      name: "Parking zones linked to street segments",
      url: "https://discover.data.vic.gov.au/dataset/parking-zones-linked-to-street-segments",
      dataShape: "tabular",
      entityType: "zone_to_street_link",
      publicAccess: "public on-street",
      confidence: "official_api",
      priority: 2,
      updateCadence: "metadata last updated 2024-06-13",
      importStrategy:
        "Use as a reference table when reconstructing Melbourne zone extents from street segments.",
      notes:
        "Not directly spatial by itself, but valuable for zone identity and linking sign plates.",
    },
    {
      id: "melbourne-sign-plates",
      owner: "City of Melbourne",
      name: "Sign plates located in each Parking zone",
      url: "https://discover.data.vic.gov.au/dataset/sign-plates-located-in-each-parking-zone",
      dataShape: "tabular",
      entityType: "zone_sign_plate",
      publicAccess: "public restriction signage",
      confidence: "official_api",
      priority: 2,
      updateCadence: "metadata record published 2025-06-26",
      importStrategy:
        "Use to enrich Melbourne rule presentation when restriction strings need sign-derived text.",
      notes:
        "Helpful as a rules enrichment source, not as the primary geometry dataset.",
    },
  ],
};

export const VICTORIA_PUBLIC_PARKING_NORMALIZED_SCHEMA = {
  source: [
    "source_id",
    "owner",
    "dataset_name",
    "source_url",
    "license",
    "fetched_at",
    "source_record_id",
  ],
  entity: [
    "entity_kind",
    "external_id",
    "name",
    "zone_type",
    "restriction_code",
    "rules_description",
    "capacity_spaces",
    "paid",
    "time_limit_minutes",
    "permit_required",
    "active_from",
    "active_to",
  ],
  geometry: [
    "boundary_geojson",
    "center_lat",
    "center_lng",
  ],
  linkage: [
    "zone_external_id",
    "bay_external_id",
    "sensor_external_id",
    "street_segment_id",
    "kerbside_id",
    "marker_id",
    "bay_id",
  ],
  telemetry: [
    "occupancy_status",
    "occupancy_updated_at",
    "availability_count",
  ],
};
