import { mergeDistinctZones } from "@/utils/zoneDeduplication";
import { RESEARCHED_PUBLIC_PARKING_ZONES } from "@/constants/researchedPublicParkingZones";

const BASE_LOCAL_COUNCIL_PARKINGS = [
  {
    id: "burgundy-one-hour-south",
    name: "Burgundy Street One Hour South",
    type: "1P",
    latitude: -37.757,
    longitude: 145.0646,
    rules: "1P public parking between Cape St and Rosanna Rd.",
  },
  {
    id: "burgundy-one-hour-north",
    name: "Burgundy Street One Hour North",
    type: "1P",
    latitude: -37.7565,
    longitude: 145.0646,
    rules: "1P public parking between Cape St and Rosanna Rd.",
  },
  {
    id: "burgundy-one-hour-west",
    name: "Burgundy Street One Hour West",
    type: "1P",
    latitude: -37.757,
    longitude: 145.0617,
    rules: "1P public parking between Stradbroke Ave and Hawdon St.",
  },
  {
    id: "burgundy-medical-core",
    name: "Burgundy Street Medical And Retail Core",
    type: "2P",
    latitude: -37.7569,
    longitude: 145.0632,
    rules: "High-turnover parking near clinics, retail, and hospital destinations.",
  },
  {
    id: "martin-two-hour",
    name: "Martin Street Two Hour Zone",
    type: "2P",
    latitude: -37.7536,
    longitude: 145.063,
    rules: "2P 8am-5pm Mon-Fri between Burgundy St and Darebin St.",
  },
  {
    id: "jika-court-precinct",
    name: "Jika Street Court Precinct",
    type: "4P",
    latitude: -37.7552,
    longitude: 145.0571,
    rules: "4P 9am-5:30pm Mon-Fri outside court and police precinct.",
  },
  {
    id: "yarra-three-hour",
    name: "Yarra Street Three Hour Zone",
    type: "3P",
    latitude: -37.7586,
    longitude: 145.0589,
    rules: "3P public parking between Mount St and Hawdon St.",
  },
  {
    id: "barkly-three-hour-south",
    name: "Barkly Place Three Hour South",
    type: "3P",
    latitude: -37.7541,
    longitude: 145.0686,
    rules: "3P public parking between Stradbroke Ave and Martin St.",
  },
  {
    id: "barkly-three-hour-north",
    name: "Barkly Place Three Hour North",
    type: "3P",
    latitude: -37.7536,
    longitude: 145.0686,
    rules: "3P public parking between Stradbroke Ave and Martin St.",
  },
  {
    id: "beverley-heidelberg-park",
    name: "Beverley Road Heidelberg Park Overflow",
    type: "4P",
    latitude: -37.7584,
    longitude: 145.0669,
    rules: "Additional public off-street parking off Beverley Rd. Banyule notes the restriction changed to 4P after the survey.",
  },
  {
    id: "collins-spring",
    name: "Collins St (Spring-Elizabeth)",
    type: "1P",
    latitude: -37.8136,
    longitude: 144.9631,
    rules: "Mon-Fri 8am-6pm, Sat 8am-12pm",
  },
  {
    id: "bourke-swanston",
    name: "Bourke St (Swanston-Russell)",
    type: "2P",
    latitude: -37.8143,
    longitude: 144.9682,
    rules: "Mon-Fri 8am-6pm",
  },
  {
    id: "lonsdale-exhibition",
    name: "Lonsdale St (Exhibition-Spring)",
    type: "3P",
    latitude: -37.8104,
    longitude: 144.9734,
    rules: "Mon-Sat 8am-6pm",
  },
  {
    id: "flinders-swanston",
    name: "Flinders St (Swanston-Russell)",
    type: "1P",
    latitude: -37.8179,
    longitude: 144.9679,
    rules: "Mon-Fri 9am-5:30pm",
  },
  {
    id: "little-collins-queen",
    name: "Little Collins St (Queen-William)",
    type: "2P",
    latitude: -37.8151,
    longitude: 144.9588,
    rules: "Mon-Fri 8am-6pm, Sat 8am-1pm",
  },
  {
    id: "elizabeth-latrobe",
    name: "Elizabeth St (Lonsdale-La Trobe)",
    type: "1P",
    latitude: -37.8098,
    longitude: 144.9634,
    rules: "Mon-Fri 8am-6pm",
  },
  {
    id: "queen-collins",
    name: "Queen St (Collins-Little Collins)",
    type: "2P",
    latitude: -37.8146,
    longitude: 144.9578,
    rules: "Mon-Sat 8am-6pm",
  },
  {
    id: "spencer-loading",
    name: "Spencer St Loading Zone",
    type: "Loading Zone",
    latitude: -37.8182,
    longitude: 144.9545,
    rules: "Mon-Fri 7am-6pm, 15 min limit",
  },
  {
    id: "latrobe-william",
    name: "La Trobe St (William-Queen)",
    type: "4P",
    latitude: -37.8093,
    longitude: 144.9594,
    rules: "Mon-Sat 8am-8pm",
  },
  {
    id: "docklands-drive",
    name: "Docklands Drive Parking",
    type: "3P",
    latitude: -37.816,
    longitude: 144.9356,
    rules: "Daily 24/7",
  },
  {
    id: "sunbury-brook-street-carpark",
    name: "Sunbury Brook Street Commuter Car Park",
    type: "Full Hour",
    latitude: -37.5793,
    longitude: 144.7285,
    rules: "Public commuter car park at Sunbury Station. PTV project page confirms Brook Street commuter car park access.",
  },
  {
    id: "watsonia-commuter-carpark",
    name: "Watsonia Station Commuter Car Park",
    type: "Full Hour",
    latitude: -37.7106,
    longitude: 145.0833,
    rules: "Public commuter car park at Watsonia Station. PTV works notice says more than 500 spaces remain available nearby.",
  },
  {
    id: "heidelberg-station-carpark",
    name: "Heidelberg Station Car Park",
    type: "Full Hour",
    latitude: -37.7573,
    longitude: 145.0607,
    rules: "Public station parking at Heidelberg Station. Added as a Full Hour commuter parking entry for the northern corridor map pass.",
  },
  {
    id: "greensborough-commuter-carpark",
    name: "Greensborough Station Commuter Car Park",
    type: "Full Hour",
    latitude: -37.7047,
    longitude: 145.103,
    rules: "Public commuter parking at Greensborough Station. Victoria's Big Build and PTV say the station precinct includes commuter car parks and 100 new car spaces.",
  },
  {
    id: "montmorency-commuter-carpark",
    name: "Montmorency Station Commuter Car Park",
    type: "Full Hour",
    latitude: -37.7161,
    longitude: 145.1225,
    rules: "Public commuter parking at Montmorency Station. Victoria's Big Build says there are 30 additional passenger car parks in and around the station.",
  },
  {
    id: "diamond-creek-station-carpark",
    name: "Diamond Creek Station Car Park",
    type: "Full Hour",
    latitude: -37.6708,
    longitude: 145.1521,
    rules: "Public station parking at Diamond Creek Station. Added as a Full Hour commuter parking entry for the northern corridor map pass.",
  },
  {
    id: "hurstbridge-station-carpark",
    name: "Hurstbridge Station Car Park",
    type: "Full Hour",
    latitude: -37.6401,
    longitude: 145.1927,
    rules: "Public station parking at Hurstbridge Station. Added as a Full Hour commuter parking entry for the northern corridor map pass.",
  },
  {
    id: "mernda-station-carpark",
    name: "Mernda Station Car Park",
    type: "Full Hour",
    latitude: -37.6005,
    longitude: 145.0954,
    rules: "Public station parking at Mernda Station. Added as a Full Hour commuter parking entry for the northern corridor map pass.",
  },
  {
    id: "ringwood-east-carpark",
    name: "Ringwood East Station Car Parks",
    type: "Full Hour",
    latitude: -37.8162,
    longitude: 145.2491,
    capacitySpaces: 467,
    rules: "Public commuter parking at Ringwood East Station. Victoria's Big Build says the completed station precinct will have 467 car parking spaces, including 12 accessible spaces.",
  },
  {
    id: "union-station-carpark",
    name: "Union Station Southern Car Park",
    type: "Full Hour",
    latitude: -37.8186,
    longitude: 145.1203,
    capacitySpaces: 290,
    rules: "Public commuter parking at Union Station. Victoria's Big Build says the northern and southern car parks together provide 290 commuter parking spaces.",
  },
  {
    id: "narre-warren-carpark",
    name: "Narre Warren Station Commuter Car Parks",
    type: "Full Hour",
    latitude: -38.0277,
    longitude: 145.3044,
    capacitySpaces: 672,
    rules: "Public commuter parking at Narre Warren Station. Victoria's Big Build says the completed station precinct includes 672 upgraded commuter car spaces.",
  },
  {
    id: "chelsea-station-carpark",
    name: "Chelsea Station Commuter Car Park",
    type: "Full Hour",
    latitude: -38.0501,
    longitude: 145.116,
    rules: "Public commuter parking at Chelsea Station. Official project fact sheet confirms commuter car parking at the station.",
  },
  {
    id: "preston-station-carparks",
    name: "Preston Station Car Parks",
    type: "Full Hour",
    latitude: -37.7388,
    longitude: 145.0006,
    capacitySpaces: 254,
    rules: "Public station car parks at Preston Station. Victoria's Big Build says the four commuter car parks total 254 spaces and remain free for station users.",
  },
  {
    id: "bell-station-carpark",
    name: "Bell Station Car Park",
    type: "Full Hour",
    latitude: -37.7456,
    longitude: 145.0009,
    capacitySpaces: 77,
    rules: "Public commuter parking at Bell Station. Victoria's Big Build says the new station car park has 77 car spaces.",
  },
  {
    id: "keon-park-carparks",
    name: "Keon Park Station Car Parks",
    type: "Full Hour",
    latitude: -37.6945,
    longitude: 145.0118,
    rules: "Public station car parks at Keon Park Station. Victoria's Big Build says the station has two car parks off High Street and Keon Parade.",
  },
  {
    id: "morwell-station",
    name: "Morwell Station Parking",
    type: "Full Hour",
    latitude: -38.2346,
    longitude: 146.3969,
    rules: "All day public parking at Morwell Station.",
  },
  {
    id: "morwell-tarwin-street-all-day",
    name: "Morwell Tarwin Street Public Parking",
    type: "Full Hour",
    latitude: -38.2354,
    longitude: 146.3962,
    rules: "All day public parking in the Morwell town centre catchment.",
  },
  {
    id: "morwell-latrobe-city-public-parking",
    name: "Morwell Civic Precinct Public Parking",
    type: "Full Hour",
    latitude: -38.2335,
    longitude: 146.3955,
    rules: "All day public parking near Latrobe City civic uses and Morwell station area.",
  },
  {
    id: "geelong-waterfront",
    name: "Geelong Waterfront Parking",
    type: "3P",
    latitude: -38.1467,
    longitude: 144.3623,
    rules: "3 hour parking, 7 days",
  },
  {
    id: "ballarat-station",
    name: "Ballarat Station Parking",
    type: "Full Hour",
    latitude: -37.5625,
    longitude: 143.8574,
    rules: "All day parking",
  },
  {
    id: "bendigo-station",
    name: "Bendigo Station Precinct",
    type: "3P",
    latitude: -36.7577,
    longitude: 144.2808,
    rules: "3 hour parking, 7 days",
  },
  {
    id: "shepparton-maude",
    name: "Shepparton CBD Maude St",
    type: "2P",
    latitude: -36.3808,
    longitude: 145.3985,
    rules: "2 hour parking, Mon-Sat 9am-5pm",
  },
  {
    id: "traralgon-franklin",
    name: "Traralgon CBD Franklin St",
    type: "2P",
    latitude: -38.1954,
    longitude: 146.5412,
    rules: "2 hour parking, Mon-Fri 8am-6pm",
  },
  {
    id: "traralgon-station",
    name: "Traralgon Station",
    type: "Full Hour",
    latitude: -38.1945,
    longitude: 146.5395,
    rules: "All day parking",
  },
  {
    id: "richmond-bridge",
    name: "Richmond Bridge Rd",
    type: "2P",
    latitude: -37.8228,
    longitude: 145.0017,
    rules: "2 hour parking 7 days 8am-8pm",
  },
  {
    id: "fitzroy-brunswick",
    name: "Fitzroy Brunswick St",
    type: "1P",
    latitude: -37.7998,
    longitude: 144.9789,
    rules: "1 hour parking Mon-Sat 8am-6pm",
  },
  {
    id: "st-kilda-acland",
    name: "St Kilda Acland St",
    type: "2P",
    latitude: -37.8683,
    longitude: 144.9805,
    rules: "2 hour parking 7 days",
  },
  {
    id: "south-melbourne-clarendon",
    name: "South Melbourne Clarendon St",
    type: "2P",
    latitude: -37.8306,
    longitude: 144.9582,
    rules: "2 hour parking Mon-Sat",
  },
  {
    id: "melbourne-flinders",
    name: "Melbourne CBD Flinders St",
    type: "1P",
    latitude: -37.8183,
    longitude: 144.9671,
    rules: "1P Mon-Fri 8am-6pm",
  },
  {
    id: "melbourne-collins",
    name: "Melbourne CBD Collins St",
    type: "2P",
    latitude: -37.8142,
    longitude: 144.9632,
    rules: "2P 7 days 8am-10pm",
  },
  {
    id: "melbourne-bourke",
    name: "Melbourne CBD Bourke St",
    type: "1P",
    latitude: -37.8136,
    longitude: 144.9631,
    rules: "1P high turnover",
  },
  {
    id: "southbank-riverside",
    name: "Southbank Riverside",
    type: "2P",
    latitude: -37.8231,
    longitude: 144.9648,
    rules: "2P 7 days",
  },
  {
    id: "docklands-harbour",
    name: "Docklands Harbour Esplanade",
    type: "2P",
    latitude: -37.8142,
    longitude: 144.944,
    rules: "2P parking",
  },
  {
    id: "carlton-lygon",
    name: "Carlton Lygon St",
    type: "1P",
    latitude: -37.803,
    longitude: 144.9677,
    rules: "1P Mon-Sat 9am-6pm",
  },
  {
    id: "collingwood-smith",
    name: "Collingwood Smith St",
    type: "2P",
    latitude: -37.8053,
    longitude: 144.9892,
    rules: "2P Mon-Sat",
  },
  {
    id: "northcote-high",
    name: "Northcote High St",
    type: "2P",
    latitude: -37.7693,
    longitude: 145.0047,
    rules: "2P parking",
  },
  {
    id: "thornbury-high",
    name: "Thornbury High St",
    type: "1P",
    latitude: -37.7634,
    longitude: 145.011,
    rules: "1P restrictions",
  },
  {
    id: "preston-high",
    name: "Preston High St",
    type: "2P",
    latitude: -37.7422,
    longitude: 145.003,
    rules: "2P 7 days",
  },
  {
    id: "coburg-sydney",
    name: "Coburg Sydney Rd",
    type: "2P",
    latitude: -37.735,
    longitude: 144.9629,
    rules: "2P parking",
  },
  {
    id: "brunswick-sydney",
    name: "Brunswick Sydney Rd",
    type: "1P",
    latitude: -37.7692,
    longitude: 144.9615,
    rules: "1P Mon-Sat",
  },
  {
    id: "st-kilda-fitzroy",
    name: "St Kilda Fitzroy St",
    type: "1P",
    latitude: -37.8615,
    longitude: 144.973,
    rules: "1P high demand",
  },
  {
    id: "port-melbourne-bay",
    name: "Port Melbourne Bay St",
    type: "2P",
    latitude: -37.8406,
    longitude: 144.9354,
    rules: "2P parking",
  },
  {
    id: "albert-park-commercial",
    name: "Albert Park Commercial Rd",
    type: "2P",
    latitude: -37.8461,
    longitude: 144.9611,
    rules: "2P 7 days",
  },
  {
    id: "middle-park-armstrong",
    name: "Middle Park Armstrong St",
    type: "1P",
    latitude: -37.8529,
    longitude: 144.9543,
    rules: "1P restrictions",
  },
  {
    id: "elwood-ormond",
    name: "Elwood Ormond Rd",
    type: "2P",
    latitude: -37.8857,
    longitude: 144.9845,
    rules: "2P beachside",
  },
  {
    id: "prahran-chapel",
    name: "Prahran Chapel St",
    type: "1P",
    latitude: -37.8507,
    longitude: 145.0069,
    rules: "1P high turnover",
  },
  {
    id: "south-yarra-toorak",
    name: "South Yarra Toorak Rd",
    type: "2P",
    latitude: -37.8406,
    longitude: 145.007,
    rules: "2P parking",
  },
  {
    id: "windsor-chapel",
    name: "Windsor Chapel St",
    type: "1P",
    latitude: -37.8592,
    longitude: 145.0033,
    rules: "1P Mon-Sat",
  },
  {
    id: "richmond-swan",
    name: "Richmond Swan St",
    type: "1P",
    latitude: -37.8269,
    longitude: 145.0007,
    rules: "1P restrictions",
  },
  {
    id: "abbotsford-victoria",
    name: "Abbotsford Victoria St",
    type: "2P",
    latitude: -37.8063,
    longitude: 145.0016,
    rules: "2P parking",
  },
  {
    id: "hawthorn-glenferrie",
    name: "Hawthorn Glenferrie Rd",
    type: "2P",
    latitude: -37.8221,
    longitude: 145.0359,
    rules: "2P Mon-Sat",
  },
  {
    id: "kew-high",
    name: "Kew High St",
    type: "2P",
    latitude: -37.8074,
    longitude: 145.0341,
    rules: "2P parking",
  },
  {
    id: "camberwell-burke",
    name: "Camberwell Burke Rd",
    type: "2P",
    latitude: -37.8316,
    longitude: 145.0572,
    rules: "2P 7 days",
  },
  {
    id: "footscray-nicholson",
    name: "Footscray Nicholson St",
    type: "2P",
    latitude: -37.8024,
    longitude: 144.8994,
    rules: "2P Mon-Sat",
  },
  {
    id: "yarraville-anderson",
    name: "Yarraville Anderson St",
    type: "2P",
    latitude: -37.8132,
    longitude: 144.8906,
    rules: "2P parking",
  },
  {
    id: "williamstown-nelson",
    name: "Williamstown Nelson Pl",
    type: "2P",
    latitude: -37.8631,
    longitude: 144.8998,
    rules: "2P waterfront",
  },
  {
    id: "seddon-charles",
    name: "Seddon Charles St",
    type: "1P",
    latitude: -37.8084,
    longitude: 144.8933,
    rules: "1P restrictions",
  },
  {
    id: "spotswood-hall",
    name: "Spotswood Hall St",
    type: "2P",
    latitude: -37.8293,
    longitude: 144.8844,
    rules: "2P parking",
  },
  {
    id: "alphington-shopping",
    name: "Alphington Shopping Village",
    type: "2P",
    latitude: -37.7808,
    longitude: 145.0308,
    rules: "2P Mon-Sat",
  },
  {
    id: "eaglemont-village",
    name: "Eaglemont Village",
    type: "1P",
    latitude: -37.7628,
    longitude: 145.0558,
    rules: "1P restrictions",
  },
  {
    id: "heidelberg-town",
    name: "Heidelberg Town Centre",
    type: "2P",
    latitude: -37.7586,
    longitude: 145.0615,
    rules: "2P shopping",
  },
  {
    id: "ivanhoe-upper-heidelberg",
    name: "Ivanhoe Upper Heidelberg",
    type: "2P",
    latitude: -37.7711,
    longitude: 145.0425,
    rules: "2P parking",
  },
  {
    id: "greensborough-main",
    name: "Greensborough Main St",
    type: "2P",
    latitude: -37.7047,
    longitude: 145.103,
    rules: "2P 7 days",
  },
  {
    id: "eltham-main",
    name: "Eltham Main Rd",
    type: "2P",
    latitude: -37.7132,
    longitude: 145.1664,
    rules: "2P parking",
  },
  {
    id: "diamond-creek-main",
    name: "Diamond Creek Main St",
    type: "2P",
    latitude: -37.6697,
    longitude: 145.1523,
    rules: "2P Mon-Sat",
  },
  {
    id: "box-hill-main",
    name: "Box Hill Main St",
    type: "2P",
    latitude: -37.8191,
    longitude: 145.1239,
    rules: "2P shopping district",
  },
  {
    id: "blackburn-south",
    name: "Blackburn South Rd",
    type: "2P",
    latitude: -37.829,
    longitude: 145.1463,
    rules: "2P parking",
  },
  {
    id: "glen-waverley-kingsway",
    name: "Glen Waverley Kingsway",
    type: "2P",
    latitude: -37.8766,
    longitude: 145.163,
    rules: "2P 7 days",
  },
  {
    id: "ringwood-maroondah",
    name: "Ringwood Maroondah Hwy",
    type: "2P",
    latitude: -37.8146,
    longitude: 145.2287,
    rules: "2P parking",
  },
  {
    id: "croydon-main",
    name: "Croydon Main St",
    type: "2P",
    latitude: -37.7936,
    longitude: 145.2832,
    rules: "2P Mon-Sat",
  },
  {
    id: "lilydale-main",
    name: "Lilydale Main St",
    type: "2P",
    latitude: -37.7557,
    longitude: 145.3509,
    rules: "2P parking",
  },
  {
    id: "caulfield-glen-eira",
    name: "Caulfield Glen Eira Rd",
    type: "2P",
    latitude: -37.8782,
    longitude: 145.0245,
    rules: "2P 7 days",
  },
  {
    id: "carnegie-koornang",
    name: "Carnegie Koornang Rd",
    type: "2P",
    latitude: -37.8879,
    longitude: 145.0557,
    rules: "2P parking",
  },
  {
    id: "bentleigh-centre",
    name: "Bentleigh Centre Rd",
    type: "2P",
    latitude: -37.9205,
    longitude: 145.0357,
    rules: "2P Mon-Sat",
  },
  {
    id: "moorabbin-station",
    name: "Moorabbin Station St",
    type: "2P",
    latitude: -37.9362,
    longitude: 145.0431,
    rules: "2P parking",
  },
  {
    id: "oakleigh-atherton",
    name: "Oakleigh Atherton Rd",
    type: "2P",
    latitude: -37.9002,
    longitude: 145.0886,
    rules: "2P 7 days",
  },
  {
    id: "clayton-road",
    name: "Clayton Clayton Rd",
    type: "2P",
    latitude: -37.9211,
    longitude: 145.1215,
    rules: "2P parking",
  },
  {
    id: "dandenong-lonsdale",
    name: "Dandenong Lonsdale St",
    type: "2P",
    latitude: -37.9874,
    longitude: 145.2152,
    rules: "2P CBD",
  },
  {
    id: "noble-park-douglas",
    name: "Noble Park Douglas St",
    type: "2P",
    latitude: -37.971,
    longitude: 145.177,
    rules: "2P parking",
  },
  {
    id: "brighton-bay",
    name: "Brighton Bay St",
    type: "2P",
    latitude: -37.9083,
    longitude: 144.9967,
    rules: "2P beachside",
  },
  {
    id: "sandringham-bay",
    name: "Sandringham Bay Rd",
    type: "2P",
    latitude: -37.9534,
    longitude: 145.0036,
    rules: "2P 7 days",
  },
  {
    id: "beaumaris-balcombe",
    name: "Beaumaris Balcombe Rd",
    type: "2P",
    latitude: -37.9869,
    longitude: 145.0382,
    rules: "2P parking",
  },
  {
    id: "mentone-como",
    name: "Mentone Como Parade",
    type: "2P",
    latitude: -37.9826,
    longitude: 145.0651,
    rules: "2P beachside",
  },
  {
    id: "mordialloc-main",
    name: "Mordialloc Main St",
    type: "2P",
    latitude: -38.0016,
    longitude: 145.0899,
    rules: "2P Mon-Sat",
  },
  {
    id: "frankston-wells",
    name: "Frankston Wells St",
    type: "2P",
    latitude: -38.1424,
    longitude: 145.1244,
    rules: "2P shopping",
  },
  {
    id: "mornington-main",
    name: "Mornington Main St",
    type: "2P",
    latitude: -38.2188,
    longitude: 145.0378,
    rules: "2P 7 days",
  },
  {
    id: "rosebud-point-nepean",
    name: "Rosebud Point Nepean Rd",
    type: "2P",
    latitude: -38.3597,
    longitude: 144.9077,
    rules: "2P beach parking",
  },
  {
    id: "sorrento-ocean-beach",
    name: "Sorrento Ocean Beach Rd",
    type: "2P",
    latitude: -38.3395,
    longitude: 144.743,
    rules: "2P coastal",
  },
  {
    id: "portsea-point-nepean",
    name: "Portsea Point Nepean Rd",
    type: "1P",
    latitude: -38.3517,
    longitude: 144.7102,
    rules: "1P beach access",
  },
  {
    id: "moe-cbd",
    name: "Moe Central Business District",
    type: "2P",
    latitude: -38.1748,
    longitude: 146.2644,
    rules: "2P Mon-Fri 9am-5pm",
  },
  {
    id: "moe-george",
    name: "Moe George St",
    type: "1P",
    latitude: -38.1752,
    longitude: 146.263,
    rules: "1P shopping district",
  },
  {
    id: "morwell-commercial",
    name: "Morwell Commercial Rd",
    type: "1P",
    latitude: -38.2347,
    longitude: 146.3978,
    rules: "1P Mon-Sat",
  },
  {
    id: "morwell-princes",
    name: "Morwell Princes Dr",
    type: "2P",
    latitude: -38.233,
    longitude: 146.3945,
    rules: "2P parking",
  },
  {
    id: "traralgon-seymour",
    name: "Traralgon Seymour St",
    type: "1P",
    latitude: -38.197,
    longitude: 146.5405,
    rules: "1P high turnover",
  },
  {
    id: "sale-raymond",
    name: "Sale Raymond St",
    type: "2P",
    latitude: -38.1069,
    longitude: 147.0688,
    rules: "2P Mon-Sat",
  },
  {
    id: "warragul-smith",
    name: "Warragul Smith St",
    type: "2P",
    latitude: -38.1606,
    longitude: 145.9322,
    rules: "2P parking",
  },
  {
    id: "warragul-station",
    name: "Warragul Station",
    type: "Full Hour",
    latitude: -38.1595,
    longitude: 145.93,
    rules: "All day parking",
  },
  {
    id: "drouin-princes",
    name: "Drouin Princes Way",
    type: "2P",
    latitude: -38.1375,
    longitude: 145.854,
    rules: "2P 7 days",
  },
  {
    id: "geelong-moorabool",
    name: "Geelong CBD Moorabool St",
    type: "2P",
    latitude: -38.1485,
    longitude: 144.3605,
    rules: "2P Mon-Sat",
  },
  {
    id: "geelong-pakington",
    name: "Geelong Pakington St",
    type: "1P",
    latitude: -38.1427,
    longitude: 144.3542,
    rules: "1P shopping",
  },
  {
    id: "ocean-grove-terrace",
    name: "Ocean Grove The Terrace",
    type: "2P",
    latitude: -38.2645,
    longitude: 144.5252,
    rules: "2P beach parking",
  },
  {
    id: "torquay-bell",
    name: "Torquay Bell St",
    type: "2P",
    latitude: -38.3311,
    longitude: 144.3187,
    rules: "2P surf coast",
  },
  {
    id: "queenscliff-hesse",
    name: "Queenscliff Hesse St",
    type: "2P",
    latitude: -38.2652,
    longitude: 144.6616,
    rules: "2P waterfront",
  },
  {
    id: "ballarat-sturt",
    name: "Ballarat CBD Sturt St",
    type: "2P",
    latitude: -37.5622,
    longitude: 143.8503,
    rules: "2P Mon-Sat",
  },
  {
    id: "ballarat-lydiard",
    name: "Ballarat Lydiard St",
    type: "1P",
    latitude: -37.5633,
    longitude: 143.8542,
    rules: "1P shopping",
  },
  {
    id: "ballarat-bridge",
    name: "Ballarat Bridge Mall",
    type: "2P",
    latitude: -37.5625,
    longitude: 143.8525,
    rules: "2P pedestrian mall",
  },
  {
    id: "bendigo-pall-mall",
    name: "Bendigo CBD Pall Mall",
    type: "2P",
    latitude: -36.757,
    longitude: 144.2794,
    rules: "2P Mon-Sat",
  },
  {
    id: "bendigo-mitchell",
    name: "Bendigo Mitchell St",
    type: "1P",
    latitude: -36.7585,
    longitude: 144.281,
    rules: "1P shopping",
  },
  {
    id: "bendigo-hargreaves",
    name: "Bendigo Hargreaves St",
    type: "2P",
    latitude: -36.759,
    longitude: 144.278,
    rules: "2P 7 days",
  },
  {
    id: "wangaratta-murphy",
    name: "Wangaratta Murphy St",
    type: "2P",
    latitude: -36.3573,
    longitude: 146.3159,
    rules: "2P parking",
  },
  {
    id: "wodonga-high",
    name: "Wodonga High St",
    type: "2P",
    latitude: -36.1213,
    longitude: 146.8874,
    rules: "2P 7 days",
  },
  {
    id: "horsham-firebrace",
    name: "Horsham Firebrace St",
    type: "2P",
    latitude: -36.7117,
    longitude: 142.1992,
    rules: "2P parking",
  },
  {
    id: "warrnambool-liebig",
    name: "Warrnambool Liebig St",
    type: "2P",
    latitude: -38.3817,
    longitude: 142.4873,
    rules: "2P coastal city",
  },
  {
    id: "colac-murray",
    name: "Colac Murray St",
    type: "2P",
    latitude: -38.3397,
    longitude: 143.5853,
    rules: "2P Mon-Sat",
  },
  {
    id: "hamilton-gray",
    name: "Hamilton Gray St",
    type: "2P",
    latitude: -37.7424,
    longitude: 142.0166,
    rules: "2P parking",
  },
  {
    id: "moe-railway-station",
    name: "Moe Railway Station",
    type: "Full Hour",
    latitude: -38.1735,
    longitude: 146.2625,
    rules: "All day parking",
  },
];

export const LOCAL_COUNCIL_PARKINGS = mergeDistinctZones(
  BASE_LOCAL_COUNCIL_PARKINGS,
  RESEARCHED_PUBLIC_PARKING_ZONES,
);
